# Generated by Django 5.2.11 on 2026-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_product_image_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('supplier_code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='suppliers', to='inventory.product')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['supplier_code'], name='suppliers_s_supplie_97d6e1_idx'), models.Index(fields=['email'], name='suppliers_s_email_971388_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx')],
            },
        ),
    ]
